spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://0.0.0.0:3307/javatechie?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#    database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9191